 //拼接html语句
 var colorStr = "";
 //存放颜色
 var colorArr = [
    { color: '#f7acbc ', textColor: '#ffffff', colorName: '鸨色' },
    { color: '#deab8a ', textColor: '#ffffff', colorName: '赤白橡' },
    { color: '#817936 ', textColor: '#ffffff', colorName: '油色' },
    { color: '#444693 ', textColor: '#ffffff', colorName: '绀桔梗' },
    { color: '#ef5b9c ', textColor: '#ffffff', colorName: '踯躅色' },
    { color: '#fedcbd ', textColor: '#000000', colorName: '肌色' },
    { color: '#7f7522 ', textColor: '#ffffff', colorName: '伽罗色' },
    { color: '#2b4490 ', textColor: '#ffffff', colorName: '花色' },
    { color: '#feeeed ', textColor: '#000000', colorName: '桜色' },
    { color: '#f47920 ', textColor: '#ffffff', colorName: '橙色' },
    { color: '#80752c ', textColor: '#ffffff', colorName: '青丹' },
    { color: '#2a5caa ', textColor: '#ffffff', colorName: '瑠璃色' },
    { color: '#f05b72 ', textColor: '#ffffff', colorName: '蔷薇色' },
    { color: '#905a3d ', textColor: '#ffffff', colorName: '灰茶' },
    { color: '#87843b ', textColor: '#ffffff', colorName: '莺色' },
    { color: '#224b8f ', textColor: '#ffffff', colorName: '琉璃绀' },
    { color: '#f15b6c ', textColor: '#ffffff', colorName: '韩红' },
    { color: '#8f4b2e ', textColor: '#ffffff', colorName: '茶色' },
    { color: '#726930 ', textColor: '#ffffff', colorName: '利久色' },
    { color: '#003a6c ', textColor: '#ffffff', colorName: '绀色' },
    { color: '#f8aba6 ', textColor: '#ffffff', colorName: '珊瑚色' },
    { color: '#87481f ', textColor: '#ffffff', colorName: '桦茶色' },
    { color: '#454926 ', textColor: '#ffffff', colorName: '媚茶' },
    { color: '#102b6a ', textColor: '#ffffff', colorName: '青蓝' },
    { color: '#f69c9f ', textColor: '#ffffff', colorName: '红梅色' },
    { color: '#5f3c23 ', textColor: '#ffffff', colorName: '枯茶' },
    { color: '#2e3a1f ', textColor: '#ffffff', colorName: '蓝海松茶' },
    { color: '#426ab3 ', textColor: '#ffffff', colorName: '杜若色' },
    { color: '#f58f98 ', textColor: '#ffffff', colorName: '桃色' },
    { color: '#6b473c ', textColor: '#ffffff', colorName: '焦茶' },
    { color: '#4d4f36 ', textColor: '#ffffff', colorName: '青钝' },
    { color: '#46485f ', textColor: '#ffffff', colorName: '胜色' },
    { color: '#ca8687 ', textColor: '#ffffff', colorName: '薄柿' },
    { color: '#faa755 ', textColor: '#ffffff', colorName: '柑子色' },
    { color: '#b7ba6b ', textColor: '#ffffff', colorName: '抹茶色' },
    { color: '#4e72b8 ', textColor: '#ffffff', colorName: '群青色' },
    { color: '#f391a9 ', textColor: '#ffffff', colorName: '薄红梅' },
    { color: '#fab27b ', textColor: '#ffffff', colorName: '杏色' },
    { color: '#b2d235 ', textColor: '#ffffff', colorName: '黄緑' },
    { color: '#181d4b ', textColor: '#ffffff', colorName: '铁绀' },
    { color: '#bd6758 ', textColor: '#ffffff', colorName: '曙色' },
    { color: '#f58220 ', textColor: '#ffffff', colorName: '蜜柑色' },
    { color: '#5c7a29 ', textColor: '#ffffff', colorName: '苔色' },
    { color: '#1a2933 ', textColor: '#ffffff', colorName: '蓝铁' },
    { color: '#d71345 ', textColor: '#ffffff', colorName: '红色' },
    { color: '#843900 ', textColor: '#ffffff', colorName: '褐色' },
    { color: '#bed742 ', textColor: '#ffffff', colorName: '若草色' },
    { color: '#121a2a ', textColor: '#ffffff', colorName: '青褐' },
    { color: '#d64f44 ', textColor: '#ffffff', colorName: '赤丹' },
    { color: '#905d1d ', textColor: '#ffffff', colorName: '路考茶' },
    { color: '#7fb80e ', textColor: '#ffffff', colorName: '若緑' },
    { color: '#0c212b ', textColor: '#ffffff', colorName: '褐返' },
    { color: '#d93a49 ', textColor: '#ffffff', colorName: '红赤' },
    { color: '#8a5d19 ', textColor: '#ffffff', colorName: '饴色' },
    { color: '#a3cf62 ', textColor: '#ffffff', colorName: '萌黄' },
    { color: '#6a6da9 ', textColor: '#ffffff', colorName: '藤纳戸' },
    { color: '#b3424a ', textColor: '#ffffff', colorName: '臙脂色' },
    { color: '#8c531b ', textColor: '#ffffff', colorName: '丁子色' },
    { color: '#769149 ', textColor: '#ffffff', colorName: '苗色' },
    { color: '#585eaa ', textColor: '#ffffff', colorName: '桔梗色' },
    { color: '#c76968 ', textColor: '#ffffff', colorName: '真赭' },
    { color: '#826858 ', textColor: '#ffffff', colorName: '丁子茶' },
    { color: '#6d8346 ', textColor: '#ffffff', colorName: '草色' },
    { color: '#494e8f ', textColor: '#ffffff', colorName: '绀蓝' },
    { color: '#bb505d ', textColor: '#ffffff', colorName: '今様色' },
    { color: '#64492b ', textColor: '#ffffff', colorName: '黄栌' },
    { color: '#78a355 ', textColor: '#ffffff', colorName: '柳色' },
    { color: '#afb4db ', textColor: '#ffffff', colorName: '藤色' },
    { color: '#987165 ', textColor: '#ffffff', colorName: '梅染' },
    { color: '#ae6642 ', textColor: '#ffffff', colorName: '土器色' },
    { color: '#abc88b ', textColor: '#ffffff', colorName: '若草色' },
    { color: '#9b95c9 ', textColor: '#ffffff', colorName: '藤紫' },
    { color: '#ac6767 ', textColor: '#ffffff', colorName: '退红色' },
    { color: '#56452d ', textColor: '#ffffff', colorName: '黄枯茶' },
    { color: '#74905d ', textColor: '#ffffff', colorName: '松叶色' },
    { color: '#6950a1 ', textColor: '#ffffff', colorName: '青紫' },
    { color: '#973c3f ', textColor: '#ffffff', colorName: '苏芳' },
    { color: '#96582a ', textColor: '#ffffff', colorName: '狐色' },
    { color: '#cde6c7 ', textColor: '#000000', colorName: '白緑' },
    { color: '#6f60aa ', textColor: '#ffffff', colorName: '菫色' },
    { color: '#b22c46 ', textColor: '#ffffff', colorName: '茜色' },
    { color: '#705628 ', textColor: '#ffffff', colorName: '黄橡' },
    { color: '#1d953f ', textColor: '#ffffff', colorName: '薄緑' },
    { color: '#867892 ', textColor: '#ffffff', colorName: '鸠羽色' },
    { color: '#a7324a ', textColor: '#ffffff', colorName: '红' },
    { color: '#4a3113 ', textColor: '#ffffff', colorName: '银煤竹' },
    { color: '#77ac98 ', textColor: '#ffffff', colorName: '千草色' },
    { color: '#918597 ', textColor: '#ffffff', colorName: '薄色' },
    { color: '#aa363d ', textColor: '#ffffff', colorName: '银朱' },
    { color: '#412f1f ', textColor: '#ffffff', colorName: '涅色' },
    { color: '#007d65 ', textColor: '#ffffff', colorName: '青緑' },
    { color: '#6f6d85 ', textColor: '#ffffff', colorName: '薄鼠' },
    { color: '#ed1941 ', textColor: '#ffffff', colorName: '赤' },
    { color: '#845538 ', textColor: '#ffffff', colorName: '胡桃色' },
    { color: '#84bf96 ', textColor: '#ffffff', colorName: '浅緑' },
    { color: '#594c6d ', textColor: '#ffffff', colorName: '鸠羽鼠' },
    { color: '#f26522 ', textColor: '#ffffff', colorName: '朱色' },
    { color: '#8e7437 ', textColor: '#ffffff', colorName: '香色' },
    { color: '#45b97c ', textColor: '#ffffff', colorName: '緑' },
    { color: '#694d9f ', textColor: '#ffffff', colorName: '菖蒲色' },
    { color: '#d2553d ', textColor: '#ffffff', colorName: '洗朱' },
    { color: '#69541b ', textColor: '#ffffff', colorName: '国防色' },
    { color: '#225a1f ', textColor: '#ffffff', colorName: '草色' },
    { color: '#6f599c ', textColor: '#ffffff', colorName: '江戸紫' },
    { color: '#b4534b ', textColor: '#ffffff', colorName: '红桦色' },
    { color: '#d5c59f ', textColor: '#ffffff', colorName: '练色' },
    { color: '#367459 ', textColor: '#ffffff', colorName: '木贼色' },
    { color: '#8552a1 ', textColor: '#ffffff', colorName: '紫' },
    { color: '#ef4136 ', textColor: '#ffffff', colorName: '红绯' },
    { color: '#cd9a5b ', textColor: '#ffffff', colorName: '肉色' },
    { color: '#007947 ', textColor: '#ffffff', colorName: '常盘色' },
    { color: '#543044 ', textColor: '#ffffff', colorName: '灭紫' },
    { color: '#c63c26 ', textColor: '#ffffff', colorName: '桦色' },
    { color: '#cd9a5b ', textColor: '#ffffff', colorName: '人色' },
    { color: '#40835e ', textColor: '#ffffff', colorName: '緑青色' },
    { color: '#63434f ', textColor: '#ffffff', colorName: '葡萄鼠' },
    { color: '#f3715c ', textColor: '#ffffff', colorName: '铅丹色' },
    { color: '#b36d41 ', textColor: '#ffffff', colorName: '土色' },
    { color: '#2b6447 ', textColor: '#ffffff', colorName: '千歳緑' },
    { color: '#7d5886 ', textColor: '#ffffff', colorName: '古代紫' },
    { color: '#a7573b ', textColor: '#ffffff', colorName: '赭' },
    { color: '#df9464 ', textColor: '#ffffff', colorName: '小麦色' },
    { color: '#005831 ', textColor: '#ffffff', colorName: '深緑' },
    { color: '#401c44 ', textColor: '#ffffff', colorName: '暗红' },
    { color: '#aa2116 ', textColor: '#ffffff', colorName: '绯色' },
    { color: '#b76f40 ', textColor: '#ffffff', colorName: '琥珀色' },
    { color: '#006c54 ', textColor: '#ffffff', colorName: '萌葱色' },
    { color: '#472d56 ', textColor: '#ffffff', colorName: '葡萄' },
    { color: '#b64533 ', textColor: '#ffffff', colorName: '丹' },
    { color: '#ad8b3d ', textColor: '#ffffff', colorName: '木兰色' },
    { color: '#375830 ', textColor: '#ffffff', colorName: '青白橡' },
    { color: '#45224a ', textColor: '#ffffff', colorName: '茄子绀' },
    { color: '#b54334 ', textColor: '#ffffff', colorName: '土' },
    { color: '#dea32c ', textColor: '#ffffff', colorName: '栀子色' },
    { color: '#274d3d ', textColor: '#ffffff', colorName: '革色' },
    { color: '#411445 ', textColor: '#ffffff', colorName: '紫绀' },
    { color: '#853f04 ', textColor: '#ffffff', colorName: '焦香' },
    { color: '#d1923f ', textColor: '#ffffff', colorName: '朽叶' },
    { color: '#375830 ', textColor: '#ffffff', colorName: '麹尘' },
    { color: '#4b2f3d ', textColor: '#ffffff', colorName: '浓色' },
    { color: '#840228 ', textColor: '#ffffff', colorName: '真红' },
    { color: '#c88400 ', textColor: '#ffffff', colorName: '萱草色' },
    { color: '#27342b ', textColor: '#ffffff', colorName: '仙斎茶' },
    { color: '#402e4c ', textColor: '#ffffff', colorName: '二蓝' },
    { color: '#7a1723 ', textColor: '#ffffff', colorName: '绯' },
    { color: '#c37e00 ', textColor: '#ffffff', colorName: '黄金' },
    { color: '#65c294 ', textColor: '#ffffff', colorName: '若竹色' },
    { color: '#c77eb5 ', textColor: '#ffffff', colorName: '菖蒲色' },
    { color: '#a03939 ', textColor: '#ffffff', colorName: '红海老茶' },
    { color: '#c37e00 ', textColor: '#ffffff', colorName: '金色' },
    { color: '#73b9a2 ', textColor: '#ffffff', colorName: '青磁色' },
    { color: '#ea66a6 ', textColor: '#ffffff', colorName: '牡丹色' },
    { color: '#8a2e3b ', textColor: '#ffffff', colorName: '浅苏芳' },
    { color: '#e0861a ', textColor: '#ffffff', colorName: '金茶' },
    { color: '#72baa7 ', textColor: '#ffffff', colorName: '青竹色' },
    { color: '#f173ac ', textColor: '#ffffff', colorName: '赤紫' },
    { color: '#8e453f ', textColor: '#ffffff', colorName: '鸢色' },
    { color: '#ffce7b ', textColor: '#000000', colorName: '卵色' },
    { color: '#005344 ', textColor: '#ffffff', colorName: '铁色' },
    { color: '#fffffb ', textColor: '#000000', colorName: '白' },
    { color: '#8f4b4a ', textColor: '#ffffff', colorName: '小豆色' },
    { color: '#fcaf17 ', textColor: '#ffffff', colorName: '山吹色' },
    { color: '#122e29 ', textColor: '#ffffff', colorName: '锖鼠' },
    { color: '#fffef9 ', textColor: '#000000', colorName: '胡粉色' },
    { color: '#892f1b ', textColor: '#ffffff', colorName: '弁柄色' },
    { color: '#ba8448 ', textColor: '#ffffff', colorName: '黄土色' },
    { color: '#293047 ', textColor: '#ffffff', colorName: '铁御纳戸' },
    { color: '#f6f5ec ', textColor: '#000000', colorName: '生成色' },
    { color: '#6b2c25 ', textColor: '#ffffff', colorName: '栗梅' },
    { color: '#896a45 ', textColor: '#ffffff', colorName: '朽叶色' },
    { color: '#00ae9d ', textColor: '#ffffff', colorName: '青緑' },
    { color: '#d9d6c3 ', textColor: '#000000', colorName: '灰白' },
    { color: '#733a31 ', textColor: '#ffffff', colorName: '海老茶' },
    { color: '#76624c ', textColor: '#ffffff', colorName: '空五倍子色' },
    { color: '#508a88 ', textColor: '#ffffff', colorName: '锖浅葱' },
    { color: '#d1c7b7 ', textColor: '#000000', colorName: '石竹色' },
    { color: '#54211d ', textColor: '#ffffff', colorName: '深绯' },
    { color: '#6d5826 ', textColor: '#ffffff', colorName: '莺茶' },
    { color: '#70a19f ', textColor: '#ffffff', colorName: '水浅葱' },
    { color: '#f2eada ', textColor: '#000000', colorName: '象牙色' },
    { color: '#78331e ', textColor: '#ffffff', colorName: '赤铜色' },
    { color: '#ffc20e ', textColor: '#ffffff', colorName: '向日葵色' },
    { color: '#50b7c1 ', textColor: '#ffffff', colorName: '新桥色' },
    { color: '#d3d7d4 ', textColor: '#000000', colorName: '乳白色' },
    { color: '#53261f ', textColor: '#ffffff', colorName: '赤褐色' },
    { color: '#fdb933 ', textColor: '#ffffff', colorName: '郁金色' },
    { color: '#00a6ac ', textColor: '#ffffff', colorName: '浅葱色' },
    { color: '#999d9c ', textColor: '#ffffff', colorName: '薄钝' },
    { color: '#f15a22 ', textColor: '#ffffff', colorName: '金赤' },
    { color: '#d3c6a6 ', textColor: '#ffffff', colorName: '砂色' },
    { color: '#78cdd1 ', textColor: '#ffffff', colorName: '白群' },
    { color: '#a1a3a6 ', textColor: '#ffffff', colorName: '银鼠' },
    { color: '#b4533c ', textColor: '#ffffff', colorName: '赤茶' },
    { color: '#c7a252 ', textColor: '#ffffff', colorName: '芥子色' },
    { color: '#008792 ', textColor: '#ffffff', colorName: '御纳戸色' },
    { color: '#9d9087 ', textColor: '#ffffff', colorName: '茶鼠' },
    { color: '#84331f ', textColor: '#ffffff', colorName: '赤锖色' },
    { color: '#dec674 ', textColor: '#ffffff', colorName: '淡黄' },
    { color: '#94d6da ', textColor: '#ffffff', colorName: '瓮覗' },
    { color: '#8a8c8e ', textColor: '#ffffff', colorName: '鼠色' },
    { color: '#f47a55 ', textColor: '#ffffff', colorName: '黄丹' },
    { color: '#b69968 ', textColor: '#ffffff', colorName: '亜麻色' },
    { color: '#afdfe4 ', textColor: '#ffffff', colorName: '水色' },
    { color: '#74787c ', textColor: '#ffffff', colorName: '薄墨色' },
    { color: '#f15a22 ', textColor: '#ffffff', colorName: '赤橙' },
    { color: '#c1a173 ', textColor: '#ffffff', colorName: '枯色' },
    { color: '#5e7c85 ', textColor: '#ffffff', colorName: '蓝鼠' },
    { color: '#7c8577 ', textColor: '#ffffff', colorName: '利休鼠' },
    { color: '#f3704b ', textColor: '#ffffff', colorName: '柿色' },
    { color: '#dbce8f ', textColor: '#ffffff', colorName: '鸟子色' },
    { color: '#76becc ', textColor: '#ffffff', colorName: '秘色' },
    { color: '#72777b ', textColor: '#ffffff', colorName: '铅色' },
    { color: '#da765b ', textColor: '#ffffff', colorName: '肉桂色' },
    { color: '#ffd400 ', textColor: '#ffffff', colorName: '黄色' },
    { color: '#90d7ec ', textColor: '#ffffff', colorName: '空色' },
    { color: '#77787b ', textColor: '#ffffff', colorName: '灰色' },
    { color: '#c85d44 ', textColor: '#ffffff', colorName: '桦色' },
    { color: '#ffd400 ', textColor: '#ffffff', colorName: '蒲公英色' },
    { color: '#009ad6 ', textColor: '#ffffff', colorName: '青' },
    { color: '#4f5555 ', textColor: '#ffffff', colorName: '钝色' },
    { color: '#ae5039 ', textColor: '#ffffff', colorName: '炼瓦色' },
    { color: '#ffe600 ', textColor: '#ffffff', colorName: '中黄' },
    { color: '#145b7d ', textColor: '#ffffff', colorName: '蓝色' },
    { color: '#6c4c49 ', textColor: '#ffffff', colorName: '煤竹色' },
    { color: '#6a3427 ', textColor: '#ffffff', colorName: '锖色' },
    { color: '#f0dc70 ', textColor: '#ffffff', colorName: '刈安色' },
    { color: '#11264f ', textColor: '#ffffff', colorName: '浓蓝' },
    { color: '#563624 ', textColor: '#ffffff', colorName: '黒茶' },
    { color: '#8f4b38 ', textColor: '#ffffff', colorName: '桧皮色' },
    { color: '#fcf16e ', textColor: '#ffffff', colorName: '黄檗色' },
    { color: '#7bbfea ', textColor: '#ffffff', colorName: '勿忘草色' },
    { color: '#3e4145 ', textColor: '#ffffff', colorName: '黒橡' },
    { color: '#8e3e1f ', textColor: '#ffffff', colorName: '栗色' },
    { color: '#decb00 ', textColor: '#ffffff', colorName: '緑黄色' },
    { color: '#33a3dc ', textColor: '#ffffff', colorName: '露草色' },
    { color: '#3c3645 ', textColor: '#ffffff', colorName: '浓鼠' },
    { color: '#f36c21 ', textColor: '#ffffff', colorName: '黄赤' },
    { color: '#cbc547 ', textColor: '#ffffff', colorName: '鶸色' },
    { color: '#228fbd ', textColor: '#ffffff', colorName: '缥色' },
    { color: '#464547 ', textColor: '#ffffff', colorName: '墨' },
    { color: '#b4532a ', textColor: '#ffffff', colorName: '代赭' },
    { color: '#6e6b41 ', textColor: '#ffffff', colorName: '海松色' },
    { color: '#2468a2 ', textColor: '#ffffff', colorName: '浅缥' },
    { color: '#130c0e ', textColor: '#ffffff', colorName: '黒' },
    { color: '#b7704f ', textColor: '#ffffff', colorName: '骆驼色' },
    { color: '#596032 ', textColor: '#ffffff', colorName: '鶸茶' },
    { color: '#2570a1 ', textColor: '#ffffff', colorName: '薄缥' },
    { color: '#281f1d ', textColor: '#ffffff', colorName: '黒铁' },
    { color: '#de773f ', textColor: '#ffffff', colorName: '黄茶' },
    { color: '#525f42 ', textColor: '#ffffff', colorName: '山鸠色' },
    { color: '#2585a6 ', textColor: '#ffffff', colorName: '薄花色' },
    { color: '#2f271d ', textColor: '#ffffff', colorName: '蝋色' },
    { color: '#c99979 ', textColor: '#ffffff', colorName: '洗柿' },
    { color: '#5f5d46 ', textColor: '#ffffff', colorName: '生壁色' },
    { color: '#1b315e ', textColor: '#ffffff', colorName: '绀青' },
    { color: '#1d1626 ', textColor: '#ffffff', colorName: '紫黒' },
];
console.log(colorArr.length)
colorArr.forEach(e => {
    colorStr += `<div class="color" style="background-color:${e.color};color:${e.textColor}" onclick="clickBox(event)">${e.color}<br>${e.colorName}</div>`
})
//拼接完字符串数组后用innerHTML把它渲染到页面中
document.getElementById("colorBox").innerHTML = colorStr;

//点击获取其背景颜色
function clickBox(event){
    document.getElementById("alert").style.animation = "";
    var e = event || window.event;
    var RGB = e.target.style.backgroundColor
    var color = RGB.colorHex()
    let link = document.createElement("input");
    document.body.appendChild(link);
    link.value = color;
    link.select();
    document.execCommand("Copy");
    document.body.removeChild(link);
    document.getElementById("alert").innerHTML="复制颜色代码("+color+")成功！快去粘贴使用吧！"
    document.getElementById("alert").style.animation = "show 3s";
}

//RGB转换十六进制工具
String.prototype.colorHex = function () {
    // RGB颜色值的正则
    var reg = /^(rgb|RGB)/;
    var color = this;
    if (reg.test(color)) {
        var strHex = "#";
        // 把RGB的3个数值变成数组
        var colorArr = color.replace(/(?:\(|\)|rgb|RGB)*/g, "").split(",");
        // 转成16进制
        for (var i = 0; i < colorArr.length; i++) {
            var hex = Number(colorArr[i]).toString(16);
            if (hex === "0") {
                hex += hex;
            }
            strHex += hex;
        }
        return strHex;
    } else {
      return String(color);
    }
};
